//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Tierra"",
            ""id"": ""45010f2c-5500-4da1-955a-f9c06f3b13d7"",
            ""actions"": [
                {
                    ""name"": ""Moverse"",
                    ""type"": ""Value"",
                    ""id"": ""6e4571f9-d6f9-4909-8c52-faadda840c83"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Saltar"",
                    ""type"": ""Button"",
                    ""id"": ""2dcaaf1e-8801-45e7-a675-690d13073af4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lanzar"",
                    ""type"": ""Button"",
                    ""id"": ""5918e8ef-3a15-4962-a5f5-480cc745d6ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Recargar"",
                    ""type"": ""Button"",
                    ""id"": ""ea972f01-c24a-4c54-b170-e144a848f368"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""01e39ae5-8916-4117-b0e5-f6365d9a18c9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""c2ddc08f-2449-4663-bc15-c29f84dbdd56"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a5e2ae30-173c-4a8d-b0fe-7237c52df2b6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4a7f829f-8283-4b1d-8e49-5e722d6fae44"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis Flecha"",
                    ""id"": ""5f023509-8366-43e8-b38f-8b9f1cb1f380"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""98e81504-a013-4510-9bfd-2c178e1a88b5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ee23628d-cd1e-4c76-a000-597a013edfbc"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""aecd8c45-9291-4c32-aefb-2a8f28011611"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02d2e458-cef1-4d5d-b4f7-cf30610cc98a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lanzar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4cc8180-2444-4fb8-9b5b-12a018c02701"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lanzar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9f64b07-fc5a-4182-bdc0-38831918fe9a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Recargar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Tierra
        m_Tierra = asset.FindActionMap("Tierra", throwIfNotFound: true);
        m_Tierra_Moverse = m_Tierra.FindAction("Moverse", throwIfNotFound: true);
        m_Tierra_Saltar = m_Tierra.FindAction("Saltar", throwIfNotFound: true);
        m_Tierra_Lanzar = m_Tierra.FindAction("Lanzar", throwIfNotFound: true);
        m_Tierra_Recargar = m_Tierra.FindAction("Recargar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Tierra
    private readonly InputActionMap m_Tierra;
    private List<ITierraActions> m_TierraActionsCallbackInterfaces = new List<ITierraActions>();
    private readonly InputAction m_Tierra_Moverse;
    private readonly InputAction m_Tierra_Saltar;
    private readonly InputAction m_Tierra_Lanzar;
    private readonly InputAction m_Tierra_Recargar;
    public struct TierraActions
    {
        private @PlayerControls m_Wrapper;
        public TierraActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Moverse => m_Wrapper.m_Tierra_Moverse;
        public InputAction @Saltar => m_Wrapper.m_Tierra_Saltar;
        public InputAction @Lanzar => m_Wrapper.m_Tierra_Lanzar;
        public InputAction @Recargar => m_Wrapper.m_Tierra_Recargar;
        public InputActionMap Get() { return m_Wrapper.m_Tierra; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TierraActions set) { return set.Get(); }
        public void AddCallbacks(ITierraActions instance)
        {
            if (instance == null || m_Wrapper.m_TierraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TierraActionsCallbackInterfaces.Add(instance);
            @Moverse.started += instance.OnMoverse;
            @Moverse.performed += instance.OnMoverse;
            @Moverse.canceled += instance.OnMoverse;
            @Saltar.started += instance.OnSaltar;
            @Saltar.performed += instance.OnSaltar;
            @Saltar.canceled += instance.OnSaltar;
            @Lanzar.started += instance.OnLanzar;
            @Lanzar.performed += instance.OnLanzar;
            @Lanzar.canceled += instance.OnLanzar;
            @Recargar.started += instance.OnRecargar;
            @Recargar.performed += instance.OnRecargar;
            @Recargar.canceled += instance.OnRecargar;
        }

        private void UnregisterCallbacks(ITierraActions instance)
        {
            @Moverse.started -= instance.OnMoverse;
            @Moverse.performed -= instance.OnMoverse;
            @Moverse.canceled -= instance.OnMoverse;
            @Saltar.started -= instance.OnSaltar;
            @Saltar.performed -= instance.OnSaltar;
            @Saltar.canceled -= instance.OnSaltar;
            @Lanzar.started -= instance.OnLanzar;
            @Lanzar.performed -= instance.OnLanzar;
            @Lanzar.canceled -= instance.OnLanzar;
            @Recargar.started -= instance.OnRecargar;
            @Recargar.performed -= instance.OnRecargar;
            @Recargar.canceled -= instance.OnRecargar;
        }

        public void RemoveCallbacks(ITierraActions instance)
        {
            if (m_Wrapper.m_TierraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITierraActions instance)
        {
            foreach (var item in m_Wrapper.m_TierraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TierraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TierraActions @Tierra => new TierraActions(this);
    public interface ITierraActions
    {
        void OnMoverse(InputAction.CallbackContext context);
        void OnSaltar(InputAction.CallbackContext context);
        void OnLanzar(InputAction.CallbackContext context);
        void OnRecargar(InputAction.CallbackContext context);
    }
}
